Repository pooranjoyb/cpp-sdk-appwrite, pull requests merged in 2025-04, with the labels that each got.

#47 Added support for pagination and queries in general.
  CMakeLists.txt
  examples/database/collection/document/listDocument.cpp
  include/Appwrite.hpp
  include/classes/Databases.hpp
  include/classes/Query.hpp
  src/services/Databases.cpp
  src/services/Query.cpp
Labels: touch-of-magic, escalate-to-the-gods

#48 Removed `json` dependency for `updateBucket` API
  examples/storage/updateBucket.cpp
  include/Utils.hpp
  src/Utils.cpp
  src/services/Storage.cpp
  tests/storage/createBucket
  tests/storage/updateBucket
Labels: touch-of-magic, code-smells

#50 refactor: removed json
  .clang-format
  examples/storage/files/updateFile.cpp
  src/services/Storage.cpp
  tests/storage/files/updateFile
Labels: chill-task, code-smells

#52 feat: create topic - [messaging]
  Makefile
  examples/messaging/topics/createTopic.cpp
  include/Utils.hpp
  include/classes/Messaging.hpp
  src/Utils.cpp
  src/services/Messaging.cpp
  src/services/Storage.cpp
Labels: touch-of-magic, chill-task, mild-mayhem

#54 feat: get and list subscribers APIs integrated
  Makefile
  examples/messaging/subscribers/getSubscriber.cpp
  examples/messaging/subscribers/listSubscribers.cpp
  include/classes/Messaging.hpp
  src/services/Messaging.cpp
Labels: touch-of-magic, chill-task

#59 feat: delete and list topics apis integrated
  Makefile
  examples/messaging/topics/deleteTopic.cpp
  examples/messaging/topics/listTopics.cpp
  include/classes/Messaging.hpp
  src/services/Messaging.cpp
Labels: chill-task

#60 feat: added listMessages api
  Makefile
  examples/messaging/messages/listMessages.cpp
  include/classes/Messaging.hpp
  src/services/Messaging.cpp
Labels: chill-task
